### ISSUE TITLE
Implement "Local Prediction" on the enV5

### ISSUE THREAD

**Issue by DavidFederl** [es-ude/BallChallenge#12]
## Tasks

- [ ] OTA Binfile Flashing
- [ ] ADXL345b polling (~800Hz)
- [ ] Run Prediction on FPGA with ADXL345b output
- [ ] Publish results of the Prediction
