### ISSUE TITLE
add commitlint and pre-commit to Ball-Challenge repo

### ISSUE THREAD

**Issue by DavidFederl** [es-ude/BallChallenge#14]
Include `commitlint.config.js` and pre-commit

## ToDo's

- [ ] Add Nodejs Configuration for Commitlint
- [ ] Add custom Commitlint configuration
- [ ] Add pre-commit with pip (include requirements.txt)
- [ ] Update README
