### ISSUE TITLE
Move BallChallenge Application from cloud repo

### ISSUE THREAD

**Issue by DavidFederl** [es-ude/BallChallenge#25]
Move Java base web front end from [elastic-ai.runtime.cloud repo](https://github.com/es-ude/elastic-ai.runtime.cloud) to this one.

## ToDo (cloud repo)

- [x] Update Gradle
- [x] Delete Ball Challenge Source Code
- [x] Move Monitor from applications folder to project root
- [x] Update `compose.yaml` to only show monitor
- [x] Add `maven-publish` plugin to runtime and setup
- [x] Add job to publish maven package to GitHub workflows
- [x] Refactor GitHub Workflows
- [x] Update Documentation

## ToDo (ball challenge repo)

- [x] Create empty gradle project in cloud folder
- [x] Import ball challenge source code from cloud repo
- [x] Update gradle config files with github package registry for runtime library
- [x] Update linting files
- [x] Update github workflows to build and publish ball challenge web application
- [x] Update provided docker compose scripts
- [x] Update Documentation
