### ISSUE TITLE
Update GitHub Workflows

### ISSUE THREAD

**Issue by DavidFederl** [es-ude/BallChallenge#32]
## ToDo's

- [x] Introduce environment variable based Beans. 
- [x] Replace jib with Dockerfile and `docker  build`
- [x] Update Image name to `ghcr.io/<repository>:<tag>`
